import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Card, CardActions, CardContent, CardMedia, Typography, Button, Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ numberOfCards }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Box className={styles.cards}>
          {numberOfCards.length && numberOfCards.map((card, index) => (
            <Card key={index} sx={{ maxWidth: 345 }}>
              <CardMedia sx={{ height: 140 }}
                image="/images.jpeg"
                title="This is the sample title"
              />
              <CardContent>
                <Typography gutterBottom variant="h5" component="div">Sample Vercel Card</Typography>
                <Typography>
                  Hello World This is my first card
                  I hope to make this very interesting
                </Typography>
              </CardContent>
              <CardActions>
                <Button size="small">Share</Button>
                <Button size="small">Bookmark</Button>
              </CardActions>
            </Card>
          ))}
        </Box>
      </main>
    </>
  );
}

// This function runs at build time and re-generates the page based on the revalidate period.
export async function getStaticProps() {
  // Fetch or generate your data here
  const numberOfCards = [1, 2, 'hello', 4]; // Example data, replace with actual data fetching logic

  // Return the props and revalidate period
  return {
    props: {
      numberOfCards,
    },
    revalidate: 10, // Regenerate the page every 10 seconds
  };
}
